services:
  app:
      # Build local Dockerfile
      build: .
      container_name: express_container
      environment:
        DB_HOST: db
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_NAME: ${DB_NAME}
        DB_PORT: ${DB_PORT}
      volumes:
        # Shared volume with below PG DB
        - data:/travelone/data
      depends_on:
      - db
      ports:
        - "3000:3000"

  db:
    image: postgres:latest
    container_name: travel-one-pg-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      # Shared volume with Express app
      - data:/travelone/data
      # Initialise DB when container is run
      - ./db_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  data: